# Generated by Django 2.2.4 on 2019-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(verbose_name='data da criação')),
                ('tipo_despesa', models.CharField(choices=[('remedio', 'Remédio'), ('roupas', 'Roupas'), ('alimentacao', 'Alimentação'), ('educacao', 'Educação'), ('transporte', 'Transporte'), ('outros', 'Outros')], max_length=15, verbose_name='tipo de despesa')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'cartão de crédito'), ('cartao_debito', 'cartão de débito'), ('cartao_crediario', 'cartão  crediário'), ('cheque', 'cheque')], max_length=15, verbose_name='forma de pagamento')),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
        ),
    ]
